#!/bin/bash
export FFTEXT=$(realpath "$(dirname $(readlink -f $BASH_SOURCE))")

if [[ $1 = "dev" ]]; then
  export FFTEXT_DEV=true
fi

find-browser() {
  path=$(which $1)
  if ! [ -z $path ]
  then
    export FFTEXT_BROWSER=$2
    export FFTEXT_BROWSER_VERSION=$($path --product-version)
  fi
}

find-browser brave-browser brave
[ -z "$FFTEXT_BROWSER" ] && find-browser chromium-browser chromium
[ -z "$FFTEXT_BROWSER" ] && find-browser google-chrome chrome
[ -z "$FFTEXT_BROWSER" ] && find-browser vivaldi vivaldi
[ -z "$FFTEXT_BROWSER" ] && find-browser microsoft-edge-stable edge
[ -z "$FFTEXT_BROWSER" ] && zenity --error --text="Chromium-based browser not found." && exit

node=$(which node)
[ -z $node ] && zenity --error --text="Node.js not found." && exit

echo "found browser: $FFTEXT_BROWSER $FFTEXT_BROWSER_VERSION"

export FFTEXT_DATA="$HOME/.config/fftext"

mkdir -p "$FFTEXT_DATA"
mkdir -p "$FFTEXT_DATA/profile/NativeMessagingHosts"
node "$FFTEXT/ext/src/createHostManifest.js"

if [[ $FFTEXT_DEV = "true" ]]; then
  echo "running in dev mode"
  rm -rf "$FFTEXT/data/profile/Default/Service\ Worker"
  $FFTEXT_BROWSER \
    --load-extension="$FFTEXT/ext" \
    --user-data-dir="$FFTEXT_DATA/profile" \
    --app="http://localhost:5173" \
    --auto-open-devtools-for-tabs \
    --enable-logging=stderr
else
  $FFTEXT_BROWSER \
    --load-extension="$FFTEXT/ext" \
    --user-data-dir="$FFTEXT_DATA/profile" \
    --app="file://$FFTEXT/app/dist/index.html" \
    --allow-file-access-from-files
fi
