#!/bin/bash
export FFTEXT=$(realpath "$(dirname $(readlink -f $BASH_SOURCE))")

if [[ $1 = "dev" ]]; then
  export FFTEXT_DEV=true
fi

# Find requirements

find-browser() {
  path=$(which $1)
  if ! [ -z $path ]
  then
    export FFTEXT_BROWSER=$2
    export FFTEXT_BROWSER_VERSION=$($path --product-version)
  fi
}

find-browser brave-browser brave
[ -z "$FFTEXT_BROWSER" ] && find-browser chromium-browser chromium
[ -z "$FFTEXT_BROWSER" ] && find-browser google-chrome chrome
[ -z "$FFTEXT_BROWSER" ] && find-browser vivaldi vivaldi
[ -z "$FFTEXT_BROWSER" ] && find-browser microsoft-edge-stable edge
[ -z "$FFTEXT_BROWSER" ] && zenity --error --text="Supported Chromium-based browser was not found!" && exit

node=$(which node)
[ -z $node ] && zenity --error --text="Node.js not found!" && exit

export FFTEXT_DATA="$HOME/.config/fftext"
mkdir -p "$FFTEXT_DATA"

# Check installation

if [[ $FFTEXT_DEV = "true" ]]; then
  export FFTEXT_DATA="$FFTEXT_DATA/dev"
else
  if [[ ! -f "$FFTEXT_DATA/installed.txt" ]]; then
    npm --prefix "$FFTEXT/host" install \
    | zenity \
      --progress \
      --title="fftext" \
      --text="Installing dependencies..." \
      --auto-close \
      --pulsate \
    && cp "$FFTEXT/fftext.desktop" "$HOME/.local/share/applications/fftext.desktop" \
    && echo "Path=$FFTEXT" >> "$HOME/.local/share/applications/fftext.desktop" \
    && echo "true" > "$FFTEXT_DATA/installed.txt"
  fi
fi

# Create host manifest

mkdir -p "$FFTEXT_DATA/$FFTEXT_BROWSER/NativeMessagingHosts"
node "$FFTEXT/ext/src/createHostManifest.js"

# Launch

if [[ $FFTEXT_DEV = "true" ]]; then
  echo "running in dev mode"
  rm -rf "$FFTEXT_DATA/$FFTEXT_BROWSER/Default/Service\ Worker"
  $FFTEXT_BROWSER \
    --load-extension="$FFTEXT/ext" \
    --user-data-dir="$FFTEXT_DATA/$FFTEXT_BROWSER" \
    --app="http://localhost:5173" \
    --auto-open-devtools-for-tabs \
    --enable-logging=stderr
else
  $FFTEXT_BROWSER \
    --load-extension="$FFTEXT/ext" \
    --user-data-dir="$FFTEXT_DATA/$FFTEXT_BROWSER" \
    --app="file://$FFTEXT/app/dist/index.html" \
    --allow-file-access-from-files
fi
